# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  flake.modules.nixos."confs/wonderland" =
    {
      config,
      lib,
      pkgs,
      modulesPath,
      ...
    }:

    {
      imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
      ];

      boot = {
        initrd.availableKernelModules = [
          "nvme"
          "xhci_pci"
          "ahci"
          "usb_storage"
          "sd_mod"
          "rtsx_pci_sdmmc"
        ];
        initrd.kernelModules = [ ];
        kernelModules = [ "kvm-amd" ];
        extraModulePackages = [ ];
      };

      fileSystems."/" = {
        device = "/dev/mapper/luks-7061dd1d-573e-41cb-949b-fea6ab474653";
        fsType = "ext4";
      };

      boot.initrd.luks.devices."luks-7061dd1d-573e-41cb-949b-fea6ab474653".device =
        "/dev/disk/by-uuid/7061dd1d-573e-41cb-949b-fea6ab474653";

      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/3263-D2BC";
        fsType = "vfat";
        options = [
          "fmask=0077"
          "dmask=0077"
        ];
      };

      swapDevices = [
        { device = "/dev/mapper/luks-343f1b27-ab09-43c7-a851-6623137a8151"; }
      ];

      hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
